### ISSUE TITLE
ansible-container build fails on OS X El Capitan

### ISSUE THREAD

**Issue by keremgocen** [ansible/django-template#1]
I'm on an old mac with 10.11.6 and boot2docker installed.

ansible --version;
> ansible 2.3.0.0
>   config file = /Users/kerem/github-stuff/ansible-container-demo/ansible.cfg
>   configured module search path = Default w/o overrides
>   python version = 2.7.13 (default, Apr  4 2017, 08:46:44) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

Ansible Container, version 0.9.1

`ansible-container build` output;

> Building Docker Engine context...	
> Starting Docker build of Ansible Container Conductor image (please be patient)...	
> ERROR	Unknown exception	
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 268, in __call__
>     getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
>   File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/container/core.py", line 150, in hostcmd_build
>     cache=kwargs['cache']
>   File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 82, in __wrapped__
>     return fn(self, *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 744, in build_conductor_image
>     nocache=not cache)
>   File "/usr/local/lib/python2.7/site-packages/docker/models/images.py", line 180, in build
>     return self.get(image_id)
>   File "/usr/local/lib/python2.7/site-packages/docker/models/images.py", line 201, in get
>     return self.prepare_model(self.client.api.inspect_image(name))
>   File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
>     return f(self, resource_id, *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/docker/api/image.py", line 262, in inspect_image
>     self._get(self._url("/images/{0}/json", image)), True
>   File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 220, in _result
>     self._raise_for_status(response)
>   File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
>     raise create_api_error_from_http_exception(e)
>   File "/usr/local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
>     raise cls(e, response=response, explanation=explanation)
> ImageNotFound: 404 Client Error: Not Found ("no such image: a: No such image: a:latest")

Is this an expected output?

**Comment by keremgocen** [comment]
I guess a missed a step in ansible-container setup, fixed when I ran `sudo pip install -e .[docker]` from within cloned ansible-container's root folder following the instructions for [running from source](http://docs.ansible.com/ansible-container/installation.html#running-from-source).

Just had to run `ansible-container build` again.
